#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use RCH\Keygen\Command\GenerateKeysCommand;
use RCH\Keygen\DependencyInjection\RCHKeygenExtension;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\DependencyInjection\ContainerBuilder;

$container = new ContainerBuilder();
$extension = new RCHKeygenExtension();

$extension->load([], $container);

$app = new Application('rch/keygen', '0.0.1');
$app
    ->add($container->get('rch.keygen.command.generate_keys'))
    ->run(new ArgvInput(), new ConsoleOutput())
;
